.TH BULKUSERADD 8 "January 26, 2025" "1.0.0" "System Administration Commands"

.SH NAME
bulkuseradd \- Bulk user creation tool for Linux systems

.SH SYNOPSIS
.B bulkuseradd
.RI [ OPTIONS ] " [USERNAMES...]"
.br
.B bulkuseradd
.RI \-f " FILE" " [OPTIONS]"

.SH DESCRIPTION
.B bulkuseradd
is a command-line tool for adding multiple users to a Linux system efficiently. It supports adding users from the command line or a file, assigning them to groups, setting default shells, passwords, UID ranges, and more.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display the help message and exit.

.TP
.BR \-f " FILE"
Specify an input file containing usernames (one username per line). This is an alternative to passing usernames directly as arguments.

.TP
.BR \-g " GROUP"
Assign users to a specific group. If the group does not exist, it will be created automatically. Default group: "users".

.TP
.BR \-u " START_UID"
Specify the starting UID for the first user. Subsequent users will get incremented UIDs. Default: 1000.

.TP
.BR \-s " SHELL"
Set the default shell for the users. Default: "/bin/bash".

.TP
.BR \-p " PASSWORD"
Set a default password for all users. Default: "Password123".

.TP
.BR \-l ", " \-\-log
Enable logging of user creation activities. By default, logs are saved to "/var/log/bulkuseradd.log".

.SH USAGE
Users can be added directly as command-line arguments or through an input file using the \fB-f\fP option.

Examples:

.TP
Add users directly from the command line:
.EX
bulkuseradd -g developers -s /bin/zsh user1 user2 user3
.EE

.TP
Add users from a file:
.EX
bulkuseradd -f usernames.txt -g developers -p SecurePass123
.EE

.TP
Specify a starting UID:
.EX
bulkuseradd -u 2000 user1 user2 user3
.EE

.TP
Enable logging:
.EX
bulkuseradd -l -f usernames.txt
.EE

.SH ERROR HANDLING
If an invalid or unsupported option is provided, \fBbulkuseradd\fP will display an error message, list available options, and terminate gracefully.

.SH LOGGING
When logging is enabled using the \fB-l\fP or \fB--log\fP option, user creation activities are recorded in \fB/var/log/bulkuseradd.log\fP.

.SH AUTHOR
Developed by Gaurav Bharane.

.SH BUGS
To report bugs or contribute to the project, please visit:
.B https://github.com/gauravbharane/bulkuseradd

.SH COPYRIGHT
This tool is licensed under the MIT License. See the license file in the source repository for more details.

.SH SEE ALSO
.B useradd(8),
.B groupadd(8),
.B passwd(1)

